### ISSUE TITLE
Crashes when target in group hit

### ISSUE THREAD

**Issue by MarkInc666** [missionpinball/mpf-mc#10]
[n2f-crash-shot-in-group.zip](https://github.com/missionpinball/mpf-mc/files/212255/n2f-crash-shot-in-group.zip)

Configs from lightscripts, shots, OB_Bug_Bash
[crash_config.txt](https://github.com/missionpinball/mpf-mc/files/212258/crash_config.txt)

[mpf-mc error.txt](https://github.com/missionpinball/mpf-mc/files/212259/mpf-mc.error.txt)

Run game.  S,  1, P, P, O, R

It starts Oogie Bug Bash and hitting R (one of the targets) that should transition from blue to green.

**Comment by toomanybrians** [comment]
```
  File "c:\python34\lib\site-packages\mpf\core\config_player.py", line 228, in config_play_callback
    priority += mode.priority
TypeError: Can't convert 'int' object to str implicitly
```
Update from testing, it's the first "priority" that's the string

**Comment by toomanybrians** [comment]
fixed in bcp-add-typing branch
