### ISSUE TITLE
auto (de)register widget_player events on slide creation/removal

### ISSUE THREAD

**Issue by toomanybrians** [missionpinball/mpf-mc#125]
Currently if you have a widget_player entry with a named slide, and that slide does not exist when the widget_player event is called, it will raise an exception since that slide is not valid.

My idea was you could register the widget_player events for the slide creation event, but that doesn't really work because you still might want to only have the widget_player event do its thing when the event from the widget_player fired.

So we need a way to fix this. Two options.

If a widget_player event fires, and that entry has a slide: setting, and that slide does not exist...

(1) We just ignore that widget_player entry and do nothing.
(2) We create a slide. (If so, do we see if that's a named slide and create it from there? But then at what priority?
(3) We somehow save the most recent widget_player entry and apply it when/if the slide is created. But that's also hard because we need to look at what mode it's from, and remove it if the mode ends.

So I think option (1) is the best? Also that is very simple to implement. Just return instead of raising an exception.

The other option (4) is we only add widget player handlers with slide entries if those slides exist, and if they do not exist, we register a new helper method to watch for that slide being created, and then register the original widget handler when that slide is created. However I think option (1) will have the same ultimate effect for much simpler code?

What do you think? cc @jabdoa2

**Comment by jabdoa2** [comment]
fixed in #126
