### ISSUE TITLE
Prevent Leaking Slide Frames

### ISSUE THREAD

**Issue by jabdoa2** [missionpinball/mpf-mc#146]
Slide_frames are created when a slide is shown but never deleted when the slide is removed. However, they are recreated when the slide is shown again.

Garbage Collector Output:
`[{'prop': <DictProperty name=ids>, 'obj': <SlideFrame frame_mode2[800, 600], current slide=slide_mode1, total slides=1>}, [<SlideFrame frame_mode2[800, 600], current slide=slide_mode1, total slides=1>], <kivy.properties.PropertyStorage object at 0x7fe401777dc8>, <kivy.properties.PropertyStorage object at 0x7fe40177b0d8>, <bound method SlideFrame.on_current of <SlideFrame frame_mode2[800, 600], current slide=slide_mode1, total slides=1>>, <bound method SlideFrame.on_disabled of <SlideFrame frame_mode2[800, 600], current slide=slide_mode1, total slides=1>>, <bound method SlideFrame.on_opacity of <SlideFrame frame_mode2[800, 600], current slide=slide_mode1, total slides=1>>, <bound method SlideFrame.on_size of <SlideFrame frame_mode2[800, 600], current slide=slide_mode1, total slides=1>>, <bound method SlideFrame._update_pos of <SlideFrame frame_mode2[800, 600], current slide=slide_mode1, total slides=1>>, <frame object at 0x7fe4017b83c8>, {'self': <mpfmc.integration.test_WidgetsAndSlides.TestSlidesAndWidgets testMethod=test_slide_on_target_of_another_mode>, 'old_frame': <SlideFrame frame_mode2[800, 600], current slide=slide_mode1, total slides=1>}]`

**Comment by toomanybrians** [comment]
will be fixed (or transformed into a new bug) by #186
