### ISSUE TITLE
Add support for bitmap / image fonts

### ISSUE THREAD

**Issue by toomanybrians** [missionpinball/mpf-mc#155]
Currently Kivy only supports TrueType fonts, which means MPF only supports TTF. The limitations of TTFs are they're (1) only single color, which limits shading effects and outlines, and (2) not animated.

We need a way to support both.

There's a type of font called a "bitmap" font which is where you have a full color image with all the chars on it, packaged with what's essentially an text file which maps regions of that image to characters. (https://71squared.com/blog/what-is-a-bitmap-font)

We should implement this for MPF. (Or perhaps implement it for Kivy, https://groups.google.com/forum/#!topic/kivy-dev/fZfT8QkDuUs)

This means people can build (and share) completely custom fonts, either manually, or using tools that create colored / outlined bitmap fonts from TTFs. This would also be useful for MPF's DMD fonts which currently are based on TTFs but have a few weird things here and there. It would be nice if we could just build our own license-free bitmap fonts for the DMD.

**Comment by qcapen** [comment]
Implemented in 0.50.  Support standard .fnt files in either .xml or text format (but not currently binary). Also supports monospaced fonts using a simple python list in the config file.

Great online tool for creating bitmap fonts from TTF: [http://kvazars.com/littera/
](http://kvazars.com/littera/)

Another useful site: [http://www.angelcode.com/products/bmfont/documentation.html](http://www.angelcode.com/products/bmfont/documentation.html)
