### ISSUE TITLE
image displayed incorrectly

### ISSUE THREAD

**Issue by MarkInc666** [missionpinball/mpf-mc#17]
title.png is garbled when displayed in a attract show
![title](https://cloud.githubusercontent.com/assets/14111078/14513509/7d58376c-01b6-11e6-8a69-aaa8ebdaef39.png)

in attract_dmd_loop.yaml

  slides:
    attract_dmd_loop_slide_6:
      widgets:
      - type: image
        image: title

![garbled_image](https://cloud.githubusercontent.com/assets/14111078/14513525/b287506c-01b6-11e6-8243-583fe4ee4884.png)

**Comment by MarkInc666** [comment]
any progress with this bug?  Still showing as distorted.

**Comment by MarkInc666** [comment]
I tried opening and saving the file in photoshop, using interlaced option and it now displays correctly.
Issue still open on non-interlaced png saved in mspaint.

**Comment by toomanybrians** [comment]
I've just spent the last 30 minutes reading about interlaced images and Python image libraries. Good find!

Looks like that support for interlaced PNGs is pretty hit-or-miss depending on the graphics library that's used. Looks like lib_SDL2 (the default we use) doesn't support interlaced PNGs. I researched that a bit and it seems like that's not a common thing and that only old versions of MS Paint produces them. :)

So we might be able to call this issue solved with a warning not to use old versions of MS Paint. Alternatively there are command line tools (even Python ones) to de-interlace images, or people can do as you did and save the image from another program.)

Either way though I think we can close this issue now that we (well, "you") got to the bottom of it.

**Comment by MarkInc666** [comment]
Ok, thanks.

But weird stuff:
This was mspaint that came with Windows 10.  So, not just old version.
In PS, I saved it as interlaced and it displayed (but with the interlaced warnings on load)

**Comment by toomanybrians** [comment]
That is weird. The libpng warning has lots of Google results too, but they seem to all be about a bug in libpng. (Though maybe in this case the warning is ok since the image was interlaced?)

I'll keep this issue open pending further investigation, but remove it as a blocker for 0.30 and clarify in the docs.

**Comment by toomanybrians** [comment]
closing because we haven't seen this problem since
