### ISSUE TITLE
Invalid JSON chars in text strings crash

### ISSUE THREAD

**Issue by toomanybrians** [missionpinball/mpf-mc#170]
If a show has a character that is not a valid JSON character, for example:

```
text: Brooks & Dunn
```

It will throw a JSON decode error when it's decoded by the MC from the JSON encoding of BCP.

Also this doesn't work:

```
text: "Brooks & Dunn"
```

We should figure out how to identify and safely encode these.

**Comment by toomanybrians** [comment]
urlencode/decode?

**Comment by jabdoa2** [comment]
Does this still exist?

**Comment by jabdoa2** [comment]
Reopen if you experience this
