### ISSUE TITLE
change the build order in travis

### ISSUE THREAD

**Issue by toomanybrians** [missionpinball/mpf-mc#175]
We should do the mac test first so that whl gets to pypi there asap. Problem now is if someone on a mac randomly tries a pip install after the windows wheels are up, they'll get a failure since the mac wheel will be about 15min behind.

**Comment by jabdoa2** [comment]
Don't they all start at the same time?

**Comment by toomanybrians** [comment]
Oh maybe you're right. In this case the mac one hasn't started yet for mpf-mc, but I also see that the mac one hasn't started for mpf, so maybe they just have a longer queue for the mac at the moment

**Comment by toomanybrians** [comment]
confirmed they all start at the same mac. Mac was just slow to start that day.
