### ISSUE TITLE
Sound files in track subfolders cause crash

### ISSUE THREAD

**Issue by GabeKnuth** [missionpinball/mpf-mc#196]
@qcapen 

When I create a subfolder under a track folder (like sounds\sfx\drums) and put files in it, I get a crash that says "Pinball.mpf_mc.mpfmc.core.audio.audio_interface.AudioException: Sound must have a valid track name"

Moving the sound file out of that folder and into the root of the track folder works. Log is attached. Look for kick-softy (it's right at the bottom).

[2016-09-27-23-43-20-mc-Gabriels-MacBook-Pro.local.log.zip](https://github.com/missionpinball/mpf-mc/files/497148/2016-09-27-23-43-20-mc-Gabriels-MacBook-Pro.local.log.zip)

**Comment by qcapen** [comment]
I can verify that this is an asset loader problem and affects all asset types.  Default values are not assigned to subfolders.

**Comment by qcapen** [comment]
Fixed in MPF 0.33.0.dev17 (MPF-MC code does not change) pull request 860.
