### ISSUE TITLE
Verify audio default settings

### ISSUE THREAD

**Issue by toomanybrians** [missionpinball/mpf-mc#20]
Seems that sounds only work if ducking: and track: is in the sound player?

**Comment by qcapen** [comment]
I will investigate.  The audio tests do not have either ducking or track in the sound player (they are specified at the asset level in the tests and ducking is only applied to the long voice sounds).

**Comment by qcapen** [comment]
I cannot reproduce this issue.  @toomanybrians are you still encountering this situation?

**Comment by toomanybrians** [comment]
I don't see this either, so I'm closing it
