### ISSUE TITLE
Add "release_events" to ducking in sounds?

### ISSUE THREAD

**Issue by GabeKnuth** [missionpinball/mpf-mc#201]
Trying to play a SFX in a mode where I need to use ducking to mute the music bed playing in the base mode. The SFX is actually a loop, and the length of time it's playing is not set in stone. That means that the typical ducking config at the sound level doesn't quite work for me. 

What I think I'd like, and feel free to tell me to go pound salt, is to see a release_event in the ducking config in addition to release_point. That would allow me to release on a ball_left event or something.

If I can enter several events, it can remain in the sounds: config where it is now. But then I got thinking about situations where someone might want to have different ducking settings based on mode in order to create some sort of effect. In that case, we'd have to have the ability to use ducking in the sound_player config. 

Thoughts? Maybe there's another way to do this. It's my first day (literally, I just dug into ducking today).

**Comment by qcapen** [comment]
In 0.32 there is another way you can do this.  There is a new 'track_controller' that can control the audio tracks with events.  There is a 'set_volume' action that you can simulate your own ducking by combining the 'set_volume' action with a 'fade' value and new 'volume' setting.  Also, I can easily add ducking support to the 'sound_player' for 0.32.  All the support is basically there now, just need to add a little validation and add it to the config spec.

**Comment by qcapen** [comment]
In 0.32 you can also 'pause' the music track (with a fade out value) as another option.  Use the 'resume' action (with a fade in value) when ready to restart the music track.  Probably better than faux ducking.

**Comment by GabeKnuth** [comment]
Cool. Both sound good to me.
