### ISSUE TITLE
Slide background color not displaying

### ISSUE THREAD

**Issue by cfbenn** [missionpinball/mpf-mc#238]
A slide will display a text widget but not change the background color.

Attached is a sample with details.

[MPF_SlideBug.zip.txt](https://github.com/missionpinball/mpf-mc/files/732455/MPF_SlideBug.zip.txt)

**Comment by toomanybrians** [comment]
`backgound_color:` is misspelled `background_colour:`.

Also note that if you fix this, the slide background is white and the text is white, so you have to change on of the colours ;) for it to show up.
