### ISSUE TITLE
Rotate & Scale widgets

### ISSUE THREAD

**Issue by toomanybrians** [missionpinball/mpf-mc#243]
This should probably apply to all widget types, not just images.

**Comment by MarkInc666** [comment]
I'd love to have proper rotation and scaling in mpf.
I need it for my bugs crawling across the screen.  I want them rotated in the direction they are moving!
Also need scaling for when using an image instead of text for stuff like "Jackpot!" animations.
Thanks!

**Comment by qcapen** [comment]
Implemented for image widgets so far (in the refactor-displays branch). Will add to other widgets next.

**Comment by qcapen** [comment]
Implemented in 0.50 for all widgets except for display and text_input.
