### ISSUE TITLE
Need alignment option for font "baseline"

### ISSUE THREAD

**Issue by toomanybrians** [missionpinball/mpf-mc#244]
From @3dmation:

This is a fairly easy thing to show. I'll suggest using the Service Menu code as an example. Inside you can scroll through to "Switch Test", "Coil Test" or "Settings". The "Settings" text the "g" is an overhanging character. The position however, should not change on a font that uses it, since where the anchor point or default position stays the same from it's "baseline" as it's traditionally called in the font world. In MPF though, it looks like it's using the center of the extents created. This is not the same thing, as an overhanging character can cause this center to be higher and lower depending on what text is in the box.

I'm not sure the solution. I'd imagine each font has it's baseline somewhere defined in it, so MPF must somehow find it and use it.

**Comment by toomanybrians** [comment]
Agree that this is a valid issue. Ironically I never found it because apparently I only use uppercase fonts. :)

We might want to add something in the `anchor_y:` setting (which is currently "top", "middle", or "bottom") to add "baseline" (which would only work with text widgets). This is assuming we can pull the baseline offset from the widget which will require a change to the way the widget size is calculated.

Currently we draw the text (using the specified font name and size) and then take the resulting bounding box and use that for positioning. But if we can get a baseline from the font, and it's set for `anchor_y: baseline` then this should be pretty straightforward.

First though I need to google to see how we can find a baseline from a Kivy label widget...

**Comment by 3dmation** [comment]
Yeah, adding a baseline option would be the best for anchor.  This btw, 
is exactly what Adobe does with their font use.

Also, this can be seen in uppercase fonts too.  It's really just about 
the overhang.  Many stylized fonts have uppercase characters that overhang.

**Comment by toomanybrians** [comment]
I investigated this a bit more and posted a message to the Kivy users group, so I think I have a handle on what needs to be done.

Long story short, font properties such as baseline are not exposed via Kivy. The next step is to look into the core library that we use with Kivy (SDL2 in our case) to see if it exposes what we need and then to patch Kivy's text provider to expose them to MPF MC.

The good news is I see `get_descent()` and `get_ascent()` methods in the SDL2 text provider, so I'll play with those to see what I can find. It might be a few weeks before I have time for this, but the good news is that it looks promising.

**Comment by toomanybrians** [comment]
Okay since this is on my mind (instead of doing the actual work I need to do), I just did a quick experiment and it looks like I can get the descent (space from baseline to lowest point in any glyph) and the ascent (from baseline to highest point in any glyph) pretty easily. This is kind of cool because it means there are probably some scenarios (or maybe all?) where we don't need to use the offset adjust settings (http://docs.missionpinball.org/en/latest/displays/widgets/positioning.html#widget-positioning-offset-adjustments). I'll probably add "text_baseline" as an option for the `anchor_y:` setting when used with text widgets.

It doesn't look like it will be too much work. I'll see if I can bump this up to try it tonight.

**Comment by toomanybrians** [comment]
You can now use `anchor_y: baseline` for text widgets to align them on the baseline of the font.

**Comment by 3dmation** [comment]
It doesn't appear to be working.  it's behaving the same way.  Here's the code I'm amending as part of the service menu code:  This section is at the bottom.

  # menu items
  service_menu_item_switch:
    type: text
    text: Switch Test
    anchor_y: text_baseline
    style: medium
    z: 100
  service_menu_item_coil:
    type: text
    text: Coil Test
    anchor_y: text_baseline
    style: medium
    z: 100
  service_menu_item_settings:
    type: text
    text: Settings
    anchor_y: text_baseline
    style: medium
    z: 100

Also, I'm using an LCD and the font is Longdon, which is a free font.

http://www.fontspace.com/roger-white/longdon-decorative

Hope that helps.
