### ISSUE TITLE
Python 3.5 and 3.6 support on Windows

### ISSUE THREAD

**Issue by jabdoa2** [missionpinball/mpf-mc#298]
Depends on #297. Test on appveyor and update installation manual

**Comment by qcapen** [comment]
The appveyor script has already been updated in the DEV branch to build wheels for Python 3.4, 3.5, and 3.6 (both 32 and 64 bit) on Windows.  Docs have not yet been updated.  The biggest roadblock is there is no P-ROC support for 3.5 and 3.6 at the moment (see MPF issue https://github.com/missionpinball/mpf/issues/935).

**Comment by qcapen** [comment]
Will add 3.5 and 3.6 Windows support to MPF appveyor script as it does not currently support them (MC does).

**Comment by jabdoa2** [comment]
Thank for caring. I pinned pypiwin32 to an old version for now so the build will still work for 3.4 and we should also be able to install 3.4 with that version

**Comment by qcapen** [comment]
Implemented in 0.50
