### ISSUE TITLE
Text widgets getting multiple event handlers

### ISSUE THREAD

**Issue by avanwinkle** [missionpinball/mpf-mc#341]
I’ve been noticing some duplicate event handlers in the logs and found one place that we might have an easy fix (but I might be overlooking something). the MC Text widget method `_process_text()` creates a variable monitor when it detects a variable in the string, and theres a comment _monitors won’t be added twice, so it’s okay to blindly call this_. 

However, the monitors are being added multiple times. One easy fix is to change `add_player_var_handler()` and `add_current_player_handler()` (lines 258 & 262) to call `events.replace_handler()` instead of `events.add_handler()`. Another option would be to detect whether a handler exists before trying to add one. 

I'm happy to make a PR to fix using either solution (or a different one). Thoughts?

**Comment by jabdoa2** [comment]
I guess the easy fix is a good one here. Eventually, I want to refactor text placeholders to run on the MPF side instead of the MC side but that will probably not happen very soon.
