### ISSUE TITLE
GStreamer errors with Kivy 1.10.1 on Windows

### ISSUE THREAD

**Issue by jabdoa2** [missionpinball/mpf-mc#356]
The following error was reported by multiple users with kivy 1.10.1 and latest dependencies:
```
(python.exe:4292): GStreamer-WARNING **: Failed to load plugin 'c:\program files\python36\share\gstreamer\bin\libass-9.dll': 'c:\program files\python36\share\gstreamer\bin\libass-9.dll': The specified procedure could not be found.

(python.exe:4292): GStreamer-WARNING **: Failed to load plugin 'c:\program files\python36\share\gstreamer\bin\libgstassrender.dll': 'c:\program files\python36\share\gstreamer\bin\libgstassrender.dll': The specified procedure could not be found.

(python.exe:4292): GStreamer-WARNING **: Failed to load plugin 'c:\program files\python36\share\gstreamer\bin\libgstpango.dll': 'c:\program files\python36\share\gstreamer\bin\libgstpango.dll': The specified procedure could not be found.

(python.exe:4292): GStreamer-WARNING **: Failed to load plugin 'c:\program files\python36\share\gstreamer\bin\libgstrsvg.dll': 'c:\program files\python36\share\gstreamer\bin\libgstrsvg.dll': The specified procedure could not be found.
WARNING: no real random source present!

(python.exe:4292): GStreamer-WARNING **: Failed to load plugin 'c:\program files\python36\share\gstreamer\bin\libharfbuzz-0.dll': 'c:\program files\python36\share\gstreamer\bin\libharfbuzz-0.dll': The specified procedure could not be found.
```
We downgraded to 1.10.0 dependencies which seem to work fine.

This seems to be this bug: https://github.com/kivy/kivy/issues/5916
Forum discussion: https://groups.google.com/forum/#!topic/mpf-users/YSLfd-GKk0Q

**Comment by xorandar** [comment]
I'm a newbie but I believe the SDL2 and GStreamer DLLs were bumping heads. My app would run, but an error dialogue box would pop up 6 or 7 times. After I deleted the Gstreamer folder from my Python's 'share' folder, the app ran without issue and still played sound. Looking in the SDL2 folder I noticed that GStreamer and SDL2 had a few of the same audio DLLs.

Here is the box that would pop six times
![error](https://user-images.githubusercontent.com/21326755/51642985-0e002c00-1f39-11e9-9b54-6b020d6a1214.PNG)

**Comment by Buld0z3r-ai** [comment]
how exactly do i downgrade all dependencies to kivy 1.10.0?

**Comment by jabdoa2** [comment]
MPF will do that when you install it. We just use the old version as dependency in MPF.

**Comment by Arunavburagohain16** [comment]
I was facing the same problem. I just reinstalled the kivy module from version 1.10 to 1.11 and now it works..

**Comment by jabdoa2** [comment]
1.11 to the rescue
