### ISSUE TITLE
Recursion in mpfmc/uix/widget.py#L960 (0.52.x) leading to crashing mc_demo

### ISSUE THREAD

**Issue by geNAZt** [missionpinball/mpf-mc#383]
In the current released version of the media controller the recursion of self.id which is not set and thus calling __get__ on kivy which returns self when the object is none (which it is since the owner calls itself) (which has since been fixed) leads to instant crashes of the mc_demo mentioned in the documentation.

**Comment by jabdoa2** [comment]
Thanks for reporting. Unfortunately this is a known bug in kivy. We fixed it in dev. We should probably backport the fix to 0.52. As a workaround you can downgrade kivy to version 1.10.1.

**Comment by jabdoa2** [comment]
https://groups.google.com/forum/m/#!topic/mpf-users/9zy3H575GfQ
