### ISSUE TITLE
Pillow, attribute getsize

### ISSUE THREAD

**Issue by Pucksnok** [missionpinball/mpf-mc#455]
Hi.

When doing some troubleshooting with https://github.com/missionpinball/mpf-mc/issues/454 and test some stuff I ended up bypassing the sound system (so I could work with mpf) with a # at line 7 in __init__.py under mpfmc/core/audio.

With this I got another error, it happened both on my own project and mc-demo.

  File "C:\Users\Johan\AppData\Local\Programs\Python\Python311\Lib\site-packages\kivy\core\text\__init__.py", line 759, in render
    options['space_width'] = self.get_extents(' ')[0]
                             ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Johan\AppData\Local\Programs\Python\Python311\Lib\site-packages\kivy\core\text\text_pil.py", line 37, in get_extents
    w, h = font.getsize(text)
           ^^^^^^^^^^^^
AttributeError: 'FreeTypeFont' object has no attribute 'getsize'

I did Google "AttributeError: 'FreeTypeFont' object has no attribute 'getsize'" and found https://github.com/tensorflow/models/issues/11040 , What I then did was to install pillow with "pip install Pillow==9.5.0", it now works and doesn't give the getsize error anymore. 

From the link: 
"We have noticed that the most recent version of the Pillow library has removed the getsize method. As a result, we are currently working on adapting our codebase to accommodate this change. In the meantime, to avoid encountering this error in your environment, we recommend installing version 9.5.0 of Pillow by using the command pip install Pillow<=9.5.0. This will allow you to continue your work smoothly until the necessary adjustments are made.".

MPF/MPF-MC seem to install Pillow 10.1.0, if I understand the link correctly getsize method isn't available in Pillow 10.1.0, nonetheless I did install Pillow 9.5.0 and it seems to fix it. Probably something that needs to be updated in the code.

**Comment by toomanybrians** [comment]
EDIT: (Now that I know what's going on) Good find! MPF-MC uses Kivy, which in turn uses Pillow (if it's there), and the latest Kivy doesn't work with the latest Pillow. Looks like the Kivy folks are aware of this too: https://github.com/kivy/kivy/issues/8427

I’ll take a look at this in the next few days, should be a quick thing.

**Comment by toomanybrians** [comment]
I investigated this (with a great tool called [pipdeptree](https://github.com/tox-dev/pipdeptree)) and found that it's actually our use of asciimatics which is pulling in Pillow, then Kivy just tries to use it since it sees it's there. Asciimatics just needs Pillow >= 2.7 or something, so it was getting Pillow 10.x. So all we have to do is specify MPF to install Pillow 9.5.0 and that fixes this.

Looks like Kivy will fix this themselves (by supporting Pillow 10.x) in Kivy 2.3, so we can remove this pinning then.
