### ISSUE TITLE
no video playback on Windows 10 or Windows 7

### ISSUE THREAD

**Issue by MarkInc666** [missionpinball/mpf-mc#51]
Python3.4 installed.
Latest version of pip, etc.

Current dev build  - using pip install mpf-mc --upgrade
Looks like no codecs installed for video.

No video displayed during run.

> C:\mpf\NBX>mpf mc
INFO : kivy : Factory: 179 symbols loaded
INFO : kivy : Image: Providers: img_tex, img_dds, img_gif, img_sdl2 (img_pil, img_ffpyplayer ignored)
INFO : kivy : Video: Provider: null(['video_ffmpeg', 'video_ffpyplayer', 'video_pyglet'] ignored)
Loading MPF-MC controller
INFO : kivy : Mission Pinball Framework Media Controller v0.30.0.dev374
INFO : kivy : Machine path: C:\mpf\NBX
INFO : kivy : Starting clock at 30.0Hz
INFO : kivy : Text: Provider: sdl2
INFO : kivy : OSC: using <thread> for socket
INFO : kivy : Window: Provider: sdl2
INFO : kivy : GL: GLEW initialization succeeded
INFO : kivy : GL: OpenGL version <b'4.4.0 NVIDIA 344.60'>
INFO : kivy : GL: OpenGL vendor <b'NVIDIA Corporation'>
INFO : kivy : GL: OpenGL renderer <b'GeForce GT 610/PCIe/SSE2'>
INFO : kivy : GL: OpenGL parsed version: 4, 4
INFO : kivy : GL: Shading version <b'4.40 NVIDIA via Cg compiler'>
INFO : kivy : GL: Texture max size <16384>
INFO : kivy : GL: Texture max units <32>
INFO : kivy : Window: auto add sdl2 input provider
INFO : kivy : Window: virtual keyboard not allowed, single mode, not docked
INFO : kivy : Base: Start application main loop
INFO : kivy : GL: NPOT texture support is available
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile

**Comment by toomanybrians** [comment]
determined that we need to get gstreamer from kivy and not pypi. Here's @MarkInc666's post in slack about it:
<img width="774" alt="screen shot 2016-05-11 at 11 23 59 am" src="https://cloud.githubusercontent.com/assets/11877564/15203492/58962740-17d2-11e6-9f1a-c651b12103da.png">

Challenge is in the past, I couldn't get setup.py to pull from a non-pypi source. Worst case we have people manually run that pip command

**Comment by toomanybrians** [comment]
traced back to a codec issue. Updated installation instructions to include how to download the complete codec pack so all video formats work
