### ISSUE TITLE
widget: add delta values, so I can move a widget +10 from its current value, rather than to absolute 10

### ISSUE THREAD

**Issue by toomanybrians** [missionpinball/mpf-mc#57]

**Comment by toomanybrians** [comment]
we need to figure out the format.. instead of value:, how about abs_value? new_value? target_value? relative bool?

**Comment by qcapen** [comment]
I like the idea of adding a 'relative' boolean setting (defaulting to false) to toggle between an absolute target value in the 'value' setting and a relative value change in the animation.

**Comment by qcapen** [comment]
The tricky part of implementing relative target values is the calculation must be done at the start of the animation and not when the widget is instantiated.  This will require a custom animation class that overloads the _initialize function and calculates the absolute target value based on the current value plus the delta specified.

**Comment by qcapen** [comment]
Implemented in 0.50 and back-porting to 0.33.x.
