### ISSUE TITLE
video not working in dev1568 May 19th - was working May 11th

### ISSUE THREAD

**Issue by MarkInc666** [missionpinball/mpf-mc#60]
Videos no longer works - called from either shows or from mode slides.  (2nd slide in my attract should play welcome.mp4 video)

C:\mpf\NBX>pip install mpf-mc --upgrade
Requirement already up-to-date: mpf-mc in c:\python34\lib\site-packages
Requirement already up-to-date: mpf>=0.30.0.dev1568 in c:\python34\lib\site-packages (from mpf-mc)
Requirement already up-to-date: pypiwin32 in c:\python34\lib\site-packages (from mpf-mc)
Requirement already up-to-date: kivy.deps.sdl2-dev in c:\python34\lib\site-packages (from mpf-mc)
Requirement already up-to-date: kivy.deps.glew in c:\python34\lib\site-packages (from mpf-mc)
Requirement already up-to-date: ruamel.yaml<0.11,>=0.10 in c:\python34\lib\site-packages (from mpf-mc)
Requirement already up-to-date: kivy.deps.gstreamer-dev in c:\python34\lib\site-packages (from mpf-mc)
Requirement already up-to-date: kivy.deps.sdl2 in c:\python34\lib\site-packages (from mpf-mc)
Requirement already up-to-date: kivy in c:\python34\lib\site-packages (from mpf-mc)
Requirement already up-to-date: mock in c:\python34\lib\site-packages (from mpf>=0.30.0.dev1568->mpf-mc)
Requirement already up-to-date: pyserial in c:\python34\lib\site-packages (from mpf>=0.30.0.dev1568->mpf-mc)
Requirement already up-to-date: ruamel.base>=1.0.0 in c:\python34\lib\site-packages (from ruamel.yaml<0.11,>=0.10->mpf-m
c)
Requirement already up-to-date: Kivy-Garden>=0.1.4 in c:\python34\lib\site-packages (from kivy->mpf-mc)
Requirement already up-to-date: six>=1.9 in c:\python34\lib\site-packages (from mock->mpf>=0.30.0.dev1568->mpf-mc)
Requirement already up-to-date: pbr>=0.11 in c:\python34\lib\site-packages (from mock->mpf>=0.30.0.dev1568->mpf-mc)
Requirement already up-to-date: requests in c:\python34\lib\site-packages (from Kivy-Garden>=0.1.4->kivy->mpf-mc)

**Comment by MarkInc666** [comment]
[2016-05-19-12-02-26-mc-REG-CSL14843.zip](https://github.com/missionpinball/mpf-mc/files/273154/2016-05-19-12-02-26-mc-REG-CSL14843.zip)

**Comment by toomanybrians** [comment]
updated installation instructions to include how to download the complete codec pack so all video formats work
