### ISSUE TITLE
Command 'mpf both' doesn't work on the Mac when in fullscreen mode.

### ISSUE THREAD

**Issue by brian90254** [missionpinball/mpf-mc#72]
The issue seems to be that starting the mc in fullscreen mode somehow causes the terminal to lose focus. Similar effect can be seen when starting 'mc' and 'game' separately, it's not possible to get back to the terminal to start 'game'.

The work-around for me is to start game first with a delay ( e.g. 'sleep 10;mpf game'), and then in second terminal window start the mc normally with 'mpf mc'.

One clue might be that this doesn't work when trying the other way around, starting mc with a delay ( e.g. 'sleep 5;mfp mc') and then game with a *longer* delay ( like 'sleep 10;mpf game').

**Comment by toomanybrians** [comment]
dup of issue in mpf rep
