### ISSUE TITLE
video widget not looping with end_behavior: loop

### ISSUE THREAD

**Issue by MarkInc666** [missionpinball/mpf-mc#76]
video widget not looping with end_behavior: loop

The following slide shows up, video plays once, stops.
Expected behavior would be to loop.

`slides:
  slide_38:
    widgets:
      - type: text
        style: tall_title
        font_size: 32
        text: ZERO FETCH
        color: bb8811
        anchor_y: top
        y: top
        z: 90
      - type: text
        style: tall_title
        font_size: 16
        anchor_y: bottom
        text: (Char_zero_timeleft)
        y: bottom
        z: 90        
      - type: text
        text: (score)
        number_grouping: true
        min_digits: 2
        style: tall_title
        font_size: 32
        color: 339966
        z: 90        
      - type: video
        video: zero
        auto_play: true
        end_behavior: loop
        z: 100        `

**Comment by toomanybrians** [comment]
done
