### ISSUE TITLE
Exception in audio_interface.Track._play_sound_on_sound_player

### ISSUE THREAD

**Issue by HarryXS** [missionpinball/mpf-mc#89]
with mpf-mc dev498 I get the following error:
Exception ignored in audio_interface.Track._play_sound_on_sound_player
Overflow error: Python int too large to convert to C long

when I want to play a wave file 26MB big.

A Cython thing maybe?

**Comment by HarryXS** [comment]
Did some tests and found out that this happens on my Linux 32bit Systems (Raspberry) and Intel Atom.
It does not happen on 64-bit.

**Comment by HarryXS** [comment]
I totaly think its a Cython thing, since long on Linux 32 bit is only 32bit.
long on 64bit is 64 bit. Dont know how this is @ windows.

Maybe long long will do the trick, but I cant figure out exactly where this happens...
(mpf mc -v -V is not possible on a raspberry since writing on the sd-card consume too much time)

**Comment by jabdoa2** [comment]
You will not see anything related to our low level audio code in -v -V anyway. This is probably an easy fix for @qcapen. Give him a few more hours to wake up ;-).

**Comment by qcapen** [comment]
Harry,  you don't happen to have ducking settings for the 26MB sound do you?  I don't see anything obvious in the code variable types that would be too small to hold the length of a 26MB sound file.  My test systems are all 64-bit at the moment so let me bring up a 32-bit system and replicate the issue on my end. I'll report back after that.

**Comment by HarryXS** [comment]
No, no ducking, but I tested a bit more and I think it has nothing to do directly with the audio core.
It is definitely a speed thing or something like that. I took a Raspberry Pi 2 today and the bug does not appear! The Pi 2 is a quadcore Arm processor but 32bit.
Back into the old Intel Atom the bug comes back.
Into the Pi B+ (single core) the same thing.
Since neither an old Intel Atom nor a Raspberry Pi B is capable of handling mpf-mc nicely and the minimum is a Pi 2 (which runs pretty fast inside a framebuffer) I would like to close this issue and just make a remark in minimum hardware required (Like quad-core Arm or something like that).

**Comment by qcapen** [comment]
I'd like to do some more testing before closing this as there could definitely be a variable type problem in the code.  I have not yet been able to get a 32-bit system setup (my 32-bit Windows VM video driver only supports OpenGL 1.1 so Kivy will not run; need to find a driver that supports 2.0 but have not had much time to investigate).  I will setup a 32-bit Ubuntu 14.04 VM when I get some time.  We won't let this issue hold up the release candidate, but will keep it active for now.  Thanks for testing this out on several platforms.

**Comment by HarryXS** [comment]
I made a HowTo for installing everything on a raspberry pi 2 or 3.
Its in the docs already.
http://docs.missionpinball.com/0.30/install/raspberry.html
This could be the perfect platform for testing 32bit but may interfere with my framebuffer things I did.

**Comment by qcapen** [comment]
Have not been able to replicate this issue.  Will close it as the OP suggested.
