### ISSUE TITLE
Windowless mode / offscreen frame buffer / no GUI

### ISSUE THREAD

**Issue by toomanybrians** [missionpinball/mpf-mc#9]
Need to make it so mpf-mc can run without a GUI, with an off screen frame buffer. This will be useful for DMD and RGB DMD games.

This has been prototyped and works. Just need to get it into the MPF-MC code. Can probably wait until 0.31 since I don't think anyone is using this yet.

**Comment by jabdoa2** [comment]
This is mostly documentation and only works on certain devices: http://docs.missionpinball.org/en/stable/install/raspberry.html

No code changes needed. Close this?
