### ISSUE TITLE
image scale needed

### ISSUE THREAD

**Issue by MarkInc666** [missionpinball/mpf-mc#90]
Quinn:  "Kivy supports a scale parameter for images, but it appears to be hard-coded with a 1.0 value in mpf.  It doesn't look like it would be too hard to add it."

Image scale needed.  maybe something like   scale_x:  scale_y:  scale_xy:
Exposed in animation as well.

**Comment by qcapen** [comment]
Replaced by issue #243

**Comment by qcapen** [comment]
Duplicate issue, closing this one.
